### ISSUE TITLE
Build failure with fmt 9.0.0

### ISSUE THREAD

**Issue by carlocab** [VowpalWabbit/vowpal_wabbit#4058]
### Describe the bug

vowpal_wabbit 9.2.0 fails to build with fmt 9.0.0.

### How to reproduce

Build vowpal_wabbit with fmt 9.0.0.

Or, if you already have a Homebrew installation handy:
```
cd "$(brew --repository homebrew/core)"
gh pr checkout 105132
brew install --build-from-source fmt
brew install --build-from-source --verbose vowpal_wabbit
```

### Version

9.2.0

### OS

macOS

### Language

C++

### Additional context

We're trying to update Homebrew's fmt at https://github.com/Homebrew/homebrew-core/pull/105132. While rebuilding dependents, we encountered the following build failure for vowpal_wabbit:

```
  /opt/homebrew/include/fmt/core.h:1732:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
    static_assert(
    ^
  /opt/homebrew/include/fmt/core.h:1753:10: note: in instantiation of function template specialization 'fmt::detail::make_value<fmt::basic_format_context<fmt::appender, char>, nonstd::sv_lite::basic_string_view<char> &>' requested here
    return make_value<Context>(val);
           ^
  /opt/homebrew/include/fmt/core.h:1875:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, nonstd::sv_lite::basic_string_view<char> &, 0>' requested here
          data_{detail::make_arg<
                        ^
  /opt/homebrew/include/fmt/core.h:1894:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, nonstd::sv_lite::basic_string_view<char>>::format_arg_store<nonstd::sv_lite::basic_string_view<char> &>' requested here
    return {std::forward<Args>(args)...};
           ^
  /opt/homebrew/include/spdlog/logger.h:90:9: note: in instantiation of function template specialization 'spdlog::logger::log_<nonstd::sv_lite::basic_string_view<char> &>' requested here
          log_(loc, lvl, fmt, std::forward<Args>(args)...);
          ^
  /opt/homebrew/include/spdlog/logger.h:96:9: note: in instantiation of function template specialization 'spdlog::logger::log<nonstd::sv_lite::basic_string_view<char> &>' requested here
          log(source_loc{}, lvl, fmt, std::forward<Args>(args)...);
          ^
  /opt/homebrew/include/spdlog/logger.h:164:9: note: in instantiation of function template specialization 'spdlog::logger::log<nonstd::sv_lite::basic_string_view<char> &>' requested here
          log(level::warn, fmt, std::forward<Args>(args)...);
          ^
  /tmp/vowpal-wabbit-20220711-46392-19otvmm/vowpal_wabbit-9.1.0/vowpalwabbit/io/logger.h:175:74: note: in instantiation of function template specialization 'spdlog::logger::warn<nonstd::sv_lite::basic_string_view<char> &>' requested here
        if (_location == output_location::compat) { _spdlog_stdout_logger->warn(fmt, std::forward<Args>(args)...); }
                                                                           ^
  /tmp/vowpal-wabbit-20220711-46392-19otvmm/vowpal_wabbit-9.1.0/vowpalwabbit/io/logger.h:317:19: note: in instantiation of function template specialization 'VW::io::details::logger_impl::out_warn<char [43], nonstd::sv_lite::basic_string_view<char> &>' requested here
      _logger_impl->out_warn(fmt, std::forward<Args>(args)...);
                    ^
  /tmp/vowpal-wabbit-20220711-46392-19otvmm/vowpal_wabbit-9.1.0/vowpalwabbit/parse_primitives.h:117:12: note: in instantiation of function template specialization 'VW::io::logger::out_warn<char [43], nonstd::sv_lite::basic_string_view<char> &>' requested here
      logger.out_warn("'{}' is not a good float, replacing with 0", s);
             ^
```

Build logs are available at https://github.com/Homebrew/homebrew-core/runs/7277894282?check_suite_focus=true. The error starts at https://github.com/Homebrew/homebrew-core/runs/7277894282?check_suite_focus=true#step:6:10145.

I don't do C++, so apologies if the issue is not actually in vowpal_wabbit. I'm happy to report this upstream if the problem lies there.

**Comment by bassmang** [comment]
Hi @carlocab 
It looks like there are some incompatibilities because of a custom formatter in VW with the newest version of fmt. I have put in a PR to resolve the issue: #4059, however I don't think we can bump the version of fmt until the next release

**Comment by carlocab** [comment]
That works for me. Thanks @bassmang!
