### ISSUE TITLE
Python build on mac os x

### ISSUE THREAD

**Issue by clustifier** [VowpalWabbit/vowpal_wabbit#380]
Hi there,

Does the python build should work on mac os x 10.9?
When I build it with:
make python
I get this error:
ld: symbol(s) not found for architecture x86_64 

Thanks,
RC
